autodock:
    image: prologic/autodock
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: always

autodocklogger:
    image: prologic/autodock-logger
    links:
        - autodock
    restart: always

autodockhipache:
    image: prologic/autodock-hipache
    links:
        - autodock
        - hipache:redis
    restart: always

hipache:
    image: prologic/hipache
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./etc/hipache/ssl:/etc/ssl
    restart: always

hello:
    image: prologic/hello
    environment:
        - VIRTUALHOST=hello.mydomain.com
        - ALIAS=hello.local
    restart: always
